    // Gulp task runner
var gulp = require('gulp'),
    // Plumber is a gulp error handler
    plumber = require('gulp-plumber'),
    // Renders SASS into CSS
    sass = require('gulp-sass'),
    // Utilitiy to send notifications to terminal
    gutil = require('gulp-util'),
    // Concatinates files
    concat = require('gulp-concat'),
    // Used for injecting headers into generated files
    header = require('gulp-header'),
    //Used for HTML templates
    fileinclude = require('gulp-file-include');

//Place to store all path/globs required for tooling
var paths = {
  sass: {
    src: './src/assets/sass/*.scss',
    dest: './build/assets/css/'
  },
  js: {
    src: ['./src/assets/js/modules/*.js', './src/assets/js/main.js'],
    dest: './build/assets/js/'
  },
  html: {
    src: './src/*.html',
    dest: './build/'
  }
};

var banner = ['/**',
 '* This is a generated file',
 '* DO NOT EDIT THIS FILE DIRECTLY. To edit this file view the README for instructions.',
 '*/',
 ''].join('\n');



//Set the default task for Gulp
gulp.task('default', ['sass', 'js', 'html']);

//Render SASS to CSS
gulp.task('sass', function(cb) {

  return gulp.src(paths.sass.src)
  .pipe(plumber({
      errorHandler: onError
    }))
  .pipe(sass())
  .pipe(header(banner))
  .pipe(gulp.dest(paths.sass.dest));

});

//Concat all JS into one file
gulp.task('js', function(cb) {

  return gulp.src(paths.js.src)
  .pipe(plumber({
      errorHandler: onError
    }))
  .pipe(concat('main.js'))
  .pipe(header(banner))
  .pipe(gulp.dest(paths.js.dest));

});

//Compile HTML files
gulp.task('html', function() {
  gulp.src(paths.html.src)
    .pipe(plumber({
      errorHandler: onError
    }))
    .pipe(fileinclude({
      prefix: '@@',
      basepath: '@file'
    }))
    .pipe(gulp.dest(paths.html.dest));
});


//function to run on any error
var onError = function (err) {
  gutil.beep();
  console.log(err);
  this.emit('end');
};
